### ISSUE TITLE
Inaccurate y-axis labelling

### ISSUE THREAD

**Issue by saxenism** [bd-R/bddashboard#14]
![image](https://user-images.githubusercontent.com/32522659/126184461-6d3e9526-5708-4721-b8a0-b40689de0e15.png)

As can be seen in the picture above by navigating to `Data Summary >> Taxonomic` we see `a` written in the y-axis labeling. This could be eliminated.

**Comment by rahulchauhan049** [comment]
# Similar Issue #15
