### ISSUE TITLE
Inaccurate axes labeling

### ISSUE THREAD

**Issue by saxenism** [bd-R/bddashboard#15]
![image](https://user-images.githubusercontent.com/32522659/126184952-1c8a06f6-cfd9-45ef-9c87-f1a707335e48.png)

As can be seen in the picture above, when we navigate to the `Taxonomic` tab, the x-axis labeling should have been the y-axis labeling, and also, `a` can be eliminated.

**Comment by rahulchauhan049** [comment]
Fixed
