### ISSUE TITLE
*Without Coordinates* option breaks 1 Guage Plot and 1 valueBox 

### ISSUE THREAD

**Issue by saxenism** [bd-R/bddashboard#24]
Due to missing validate statements for the responsible plots, when a dataset without coordinates is downloaded, a error comes up instead of the message from validate function.

![image](https://user-images.githubusercontent.com/32522659/127268816-4a66492f-445a-404d-9df8-35c8c7e798aa.png)

![image](https://user-images.githubusercontent.com/32522659/127268880-bf1c0f15-670d-4958-898a-173f9b124f90.png)

**Comment by rahulchauhan049** [comment]
Fixed in commit
